name: fmta_dev
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
    - uses: borales/actions-yarn@v2.3.0
