name: fmta_dev
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
    - uses: borales/actions-yarn@v2.3.0
    - name: Create deployment artifact
      run: tar -czf app.tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
  web-deploy:
    needs: build
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
       uses: actions/checkout@master
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: build
        path: build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/admin-prod/